"""pricing

Revision ID: 0bf05736eaf9
Revises: f621a9d74130
Create Date: 2026-09-27 12:53:58.254069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf05736eaf9'
down_revision: Union[str, Sequence[str], None] = 'f621a9d74130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('loose', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cib', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('graded', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('box_only', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('manual_only', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'captured_on', name='uq_snapshot_product_day')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_snapshots_captured_on'), ['captured_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_snapshots_product_id'), ['product_id'], unique=False)

    op.create_table('scrape_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('snapshot_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_errors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_errors_run_id'), ['run_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('last_priced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('last_priced_at')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('scrape_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_errors_run_id'))
        batch_op.drop_index(batch_op.f('ix_scrape_errors_created_at'))

    op.drop_table('scrape_errors')
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_snapshots_product_id'))
        batch_op.drop_index(batch_op.f('ix_price_snapshots_captured_on'))

    op.drop_table('price_snapshots')
    op.drop_table('settings')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
