"""collection sharing

Revision ID: 3821b5048a47
Revises: 0f4a0668ad48
Create Date: 2026-09-27 13:35:11.063576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3821b5048a47'
down_revision: Union[str, Sequence[str], None] = '0f4a0668ad48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_collection', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('share_paid', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('share_paid')
        batch_op.drop_column('share_collection')

    # ### end Alembic commands ###
