"""acquired from

Revision ID: 700c703963be
Revises: 3821b5048a47
Create Date: 2026-09-27 14:01:50.417743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700c703963be'
down_revision: Union[str, Sequence[str], None] = '3821b5048a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acquired_from', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_column('acquired_from')

    # ### end Alembic commands ###
