"""initial schema

Revision ID: f621a9d74130
Revises: 
Create Date: 2026-09-27 12:41:05.424625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f621a9d74130'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('era', sa.String(length=64), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('handheld', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('pricecharting_slug', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_platforms_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('upc', sa.String(length=32), nullable=True),
    sa.Column('pricecharting_id', sa.String(length=32), nullable=True),
    sa.Column('pricecharting_url', sa.String(length=512), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pricecharting_id', name='uq_products_pricecharting_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_upc'), ['upc'], unique=False)

    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=False),
    sa.Column('has_item', sa.Boolean(), nullable=False),
    sa.Column('has_box', sa.Boolean(), nullable=False),
    sa.Column('has_manual', sa.Boolean(), nullable=False),
    sa.Column('has_inserts', sa.Boolean(), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('sold_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sold_date', sa.Date(), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_collection_items_status'))
        batch_op.drop_index(batch_op.f('ix_collection_items_product_id'))

    op.drop_table('collection_items')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_upc'))
        batch_op.drop_index(batch_op.f('ix_products_title'))
        batch_op.drop_index(batch_op.f('ix_products_platform_id'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platforms_slug'))
        batch_op.drop_index(batch_op.f('ix_platforms_brand'))

    op.drop_table('platforms')
    # ### end Alembic commands ###
